---

- name: download pkg
  get_url:
    url: https://download.elastic.co/kibana/kibana/kibana-3.1.2.tar.gz
    dest: /tmp/kibana-3.1.2.tar.gz

- name: install
  unarchive:
    src: /tmp/kibana-3.1.2.tar.gz
    dest: /var/www
    copy: no
    creates: /var/www/kibana-3.1.2

- name: symlink
  file:
    path: /var/www/html/kibana3
    src: /var/www/kibana-3.1.2
    state: link

- name: get gist dashboards
  get_url:
    url: "https://gist.githubusercontent.com/{{item.gist}}/raw"
    dest: "/var/www/html/kibana3/app/dashboards/{{item.dest}}"
  with_items: kibana_gist_views

#- name: load dashboards into es
#  uri:
#    url: "http://localhost:9200/kibana-int/dashboard/{{item.dest}}"
#    method: PUT
#    body: "{{ lookup('file','/var/www/html/kibana3/app/dashboards/'+item.dest) }}"
#    body_format: raw
#    status_code: 201
#  with_items: kibana_views

- name: get gist pages
  get_url:
    url: "https://gist.githubusercontent.com/{{item.gist}}/raw"
    dest: "{{item.dest}}"
  with_items: kibana_gist_pages

- name: config template
  template:
    src: "{{ item }}.j2"
    dest: "/var/www/html/kibana3/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - config.js

