---

- name: download pkg
  get_url:
    url: https://download.elastic.co/kibana/kibana/kibana-3.1.2.tar.gz
    dest: /tmp/kibana-3.1.2.tar.gz

- name: install
  unarchive:
    src: /tmp/kibana-3.1.2.tar.gz
    dest: /var/www
    copy: no
    creates: /var/www/kibana-3.1.2

- name: symlink
  file:
    path: /var/www/html/kibana3
    src: /var/www/kibana-3.1.2
    state: link

- name: get views
  get_url:
    url: "{{item.url}}"
    dest: "/var/www/html/kibana3/app/dashboards/{{item.dest}}"
  with_items: kibana_views

- name: adjust es source
  lineinfile:
    dest: /var/www/html/kibana3/config.js
    regexp: "elasticsearch: "
    line: "elasticsearch: {{kibana_url}},"

